'use client';
import { useEffect, useMemo, useState } from 'react';
import AppShell from '../../components/AppShell';
import StatusBadge from '../../components/StatusBadge';
import DataError from '../../components/DataError';
import { getSupabase } from '../../lib/supabase';

export default function Dashboard(){
 const [tasks,setTasks]=useState([]),[loans,setLoans]=useState([]),[error,setError]=useState('');
 useEffect(()=>{load();const s=getSupabase();const c=s.channel('dash-live').on('postgres_changes',{event:'*',schema:'public',table:'tasks'},load).on('postgres_changes',{event:'*',schema:'public',table:'loans'},load).subscribe();return()=>s.removeChannel(c)},[]);
 async function load(){const s=getSupabase();const [a,b]=await Promise.all([s.from('tasks').select('*').order('due_date'),s.from('loans').select('*').order('amount',{ascending:false})]);if(a.error||b.error)setError(a.error?.message||b.error?.message);else{setTasks(a.data||[]);setLoans(b.data||[])}}
 const today=new Date().toISOString().slice(0,10);const open=tasks.filter(t=>t.status!=='Complete');const overdue=open.filter(t=>t.due_date&&t.due_date<today);const blocked=open.filter(t=>t.status==='Blocked');const pipeline=loans.reduce((n,l)=>n+Number(l.amount||0),0);const byArea=useMemo(()=>Object.entries(open.reduce((a,t)=>(a[t.area]=(a[t.area]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]),[tasks]);
 return <AppShell title="Executive Dashboard" subtitle="What needs attention across every business"><DataError message={error}/><section className="metrics"><div className="metric"><span>Open tasks</span><strong>{open.length}</strong></div><div className="metric danger"><span>Overdue</span><strong>{overdue.length}</strong></div><div className="metric warning"><span>Blocked</span><strong>{blocked.length}</strong></div><div className="metric"><span>Mortgage pipeline</span><strong>${pipeline.toLocaleString()}</strong></div></section><section className="twoCol"><div className="panel"><div className="panelHead"><h2>Immediate attention</h2></div><div className="taskList">{[...overdue,...blocked.filter(b=>!overdue.some(o=>o.id===b.id)),...open.filter(t=>!overdue.some(o=>o.id===t.id)&&t.status!=='Blocked')].slice(0,8).map(t=><div className="taskRow" key={t.id}><div><strong>{t.title}</strong><small>{t.area} · {t.owner} · Due {t.due_date||'TBD'}</small></div><StatusBadge status={t.status}/></div>)}</div></div><div className="panel"><div className="panelHead"><h2>Workload by business</h2></div>{byArea.map(([area,count])=><div className="barRow" key={area}><span>{area}</span><div className="bar"><i style={{width:`${Math.min(100,count*14)}%`}}/></div><strong>{count}</strong></div>)}</div></section><section className="panel"><div className="panelHead"><h2>Mortgage pipeline</h2></div><div className="tableWrap"><table><thead><tr><th>Loan</th><th>Amount</th><th>Stage</th><th>Owner</th><th>Expected close</th></tr></thead><tbody>{loans.map(l=><tr key={l.id}><td>{l.name}</td><td>${Number(l.amount).toLocaleString()}</td><td><StatusBadge status={l.stage}/></td><td>{l.owner}</td><td>{l.expected_close||'TBD'}</td></tr>)}</tbody></table></div></section></AppShell>
}
